=== Stanly0407/epam-task-xml-parsers/src/main/resources/gems.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://gems.com/gems"
        xmlns:tns="http://gems.com/gems"
        elementFormDefault="qualified">

    <element name="gem" type="tns:GemType" abstract="true"/>
    <element name="precious-stone" type="tns:PreciousStoneType" substitutionGroup="tns:gem"/>
    <element name="semiprecious-stone" type="tns:SemipreciousStoneType" substitutionGroup="tns:gem"/>

    <element name="gems">
        <complexType>
            <sequence>
                <element ref="tns:gem" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="GemType">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <minLength value="3"/>
                        <maxLength value="50"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="extraction-place">
                <simpleType>
                    <restriction base="string">
                        <minLength value="3"/>
                        <maxLength value="50"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="visual-parameters" type="tns:VisualParameters"/>
        </sequence>
        <attribute name="certificate-number" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="(\\d){4,19}"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="PreciousStoneType">
        <complexContent>
            <extension base="tns:GemType">
                <sequence>
                    <element name="origin-type">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="ORGANIC"/>
                                <enumeration value="MINERAL"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="carats" type="double" default="0"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="SemipreciousStoneType">
        <complexContent>
            <extension base="tns:GemType">
                <sequence>
                    <element name="weight" type="double"/>
                </sequence>
                <attribute name="ornamental-type" use="required" default="0">
                    <simpleType>
                        <restriction base="positiveInteger">
                            <pattern value="[1-3]"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="VisualParameters">
        <sequence>
            <element name="color" type="string"/>
            <element name="transparent-type" default="NOT_DETERMINED">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="TRANSPARENT"/>
                        <enumeration value="SEMI_TRANSPARENT"/>
                        <enumeration value="INTRANSPARENT"/>
                        <enumeration value="NOT_DETERMINED"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="stone-planes" type="positiveInteger"/>
    </complexType>

</schema>

=== Stanly0407/epam-task-xml-parsers/src/main/resources/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://gems.com/gems"
      xsi:schemaLocation="http://gems.com/gems gems.xsd">

    <precious-stone certificate-number="PS3333O333PLP">
        <name>Rubine</name>
        <extraction-place>Southern Urals</extraction-place>
        <visual-parameters>
            <color>red-pink</color>
            <transparent-type>TRANSPARENT</transparent-type>
            <stone-planes>36</stone-planes>
        </visual-parameters>
        <origin-type>MINERAL</origin-type>
        <carats>10</carats>
    </precious-stone>

    <precious-stone certificate-number="PS-G3PLM023455">
        <name>Sapphire</name>
        <extraction-place>Madagascar</extraction-place>
        <visual-parameters>
            <color>dark blue</color>
            <transparent-type>SEMI_TRANSPARENT</transparent-type>
            <stone-planes>24</stone-planes>
        </visual-parameters>
        <origin-type>MINERAL</origin-type>
        <carats>8</carats>
    </precious-stone>

    <semiprecious-stone certificate-number="SPS2598PPL2" ornamental-type="2">
        <name>Amethyst</name>
        <extraction-place>Kola Peninsula</extraction-place>
        <visual-parameters>
            <color>violet</color>
            <transparent-type>TRANSPARENT</transparent-type>
            <stone-planes>12</stone-planes>
        </visual-parameters>
        <weight>5</weight>
    </semiprecious-stone>

    <semiprecious-stone certificate-number="SPS2525L2886P9" ornamental-type="1">
        <name>Garnet</name>
        <extraction-place>Kola Peninsula</extraction-place>
        <visual-parameters>
            <color>red</color>
            <transparent-type>NOT_DETERMINED</transparent-type>
            <stone-planes>54</stone-planes>
        </visual-parameters>
        <weight>10</weight>
    </semiprecious-stone>
</gems>
